version: '1.0'
services:
  app:
    image: app-utp-backend
    ports:
      - 4050:4050
    depends_on:
      - db
    networks:
      - network_backend
    environment:
      - PORT=4050
      - BASE_URL=http://localhost:4050
      - BD_NAME=databaseutp
      - BD_USERNAME=root
      - BD_PASSWORD=root
      - BD_HOST=db # Nombre del servicio de la base de datos
      - BD_PORT=3306
      - SECRET_KEY_JWT=c7&5ux#8pa3ay-kUS2Ok
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: databaseutp
    ports:
      - 3306:3306
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - network_backend
networks:
  network_backend:
    driver: bridge
  
  

  