version: '1.0'

services:
  

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: databaseutp
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    image: app-utp-backend
    ports:
      - 4050:4050
    depends_on:
      - db

  